### ISSUE TITLE
Please correct your tests

### ISSUE THREAD

**Issue by xelinorg** [Devskiller/devskiller-sample-react-calculator#14]
https://github.com/Devskiller/devskiller-sample-react-calculator/blob/33a9bb9c02c2ed7ddcf7b3fead35a4e7b900efae/src/App.test.tsx#L28

1+2*3/4=  equals to 2.25 and not 2.5

**Comment by xemlock** [comment]
1 + 2*3/4 = 1 + 6/4 = 1 + 1.5 = 2.5
